import type { Metadata } from "next"
import "./globals.css"

import ReactQueryProvider from "@/providers/ReactQueryProvider"
import { Toaster } from "sonner"
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  )
}